<?php
/**
 * Renderiza una tabla en base a un modelo.
 *
 * @author Andres Hal
 * 
 * @param array $Modelo modelo con los resultados a mostrar
 * @param array $Campos array con los que se quieren mostrar de la tabla
 * @return partial
 */
?>
 
	<div id="datagrid">
		<table  border="1px" width="100%"  class="paginado">
		<thead><tr>
			<?php foreach( $Campos  as $titulo => $valor): ?>
				<th> <?php echo $titulo ?></th>
			<?php endforeach; ?>
		</tr></thead>
                <tbody>
		       <? foreach( $Model->items as $model):
				echo tr_color_class( 'tr_primary', 'tr_secondary' );
					foreach($Campos as  $campos): ?>
					    <td><?php echo $model->$campos ?></td>
				       <?php endforeach; ?>
				</tr>
			<?php endforeach; ?>
		</tbody></table>
        	<?php	View::partial('paginators/'. $Paginator, false, array('page' => $Model ,'url' => $Url)); ?>
	</div>