<!DOCTYPE html>

<html>

<head>
<meta name="viewport" content="width=device-width, initial-scale=1">    

<meta charset="UTF-8">
<link rel="shortcut icon" href="http://www.wmr.skn1.com/default/public/img/logowmr.png" />
<title>WMR Notas</title>

  <?php Tag::css('bienvenida'); ?>
  <?php Tag::css('style'); ?>
    
   
  <link href="http://localhost/wmr2019/default/public/css/bootstrap.min.css" rel="stylesheet" type="text/css">
  <link href="http://localhost/wmr2019/default/public/css/custom.css" rel="stylesheet" type="text/css">

  <link rel="stylesheet" href="http://localhost/wmr2019/default/public/css/bootstrap.min.css">
  <link rel="stylesheet" href="http://localhost/wmr2019/default/public/css/animate.css">
  <?php Tag::css('bienvenida'); ?>
   
    
  <?php echo Html::includeCss() ?>

  <script src="http://localhost/wmr2019/default/public/javascript/jquery.min.js"></script> 
  <script src="http://localhost/wmr2019/default/public/javascript/bootstrap.min.js"></script>
 <?php echo Tag::js('funciones') ?>
 <script src="http://localhost/wmr2019/default/public/javascript/jquery.placeholder.min.js"></script>
  <!-- Waypoints -->
  <script src="http://localhost/wmr2019/default/public/javascript/jquery.waypoints.min.js"></script>
  <!-- Main JS -->
  <script src="http://localhost/wmr2019/default/public/javascript/main.js"></script>
  


</head>

<body >

    <div class="container">

        

          

            <?php //View::partial('kumbia/head') ?>

            <?php View::partial('kumbia/menu') ?>

            <?php //View::partial('kumbia/sidebar1') ?>

            <?php //View::partial('kumbia/sidebar2') ?>

            <?php View::content(); ?>

            <?php //View::partial('kumbia/footer') ?>

        

    </div>

   


</body>

</html>

